# -*- coding: utf-8 -*-
"""dw_association.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r1UDisCIP78JvB367JSxzZAQghy-iG1A
"""

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
import pandas as pd
import numpy as np

from mlxtend.frequent_patterns import apriori, association_rules
from sklearn.preprocessing import KBinsDiscretizer

import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("crypto_mining_dataset.csv")

print("Shape:", df.shape)
df.head()

features = [
    "price_usd",
    "vol_24h",
    "market_cap",
    "chg_24h",
    "chg_7d"
]

df_mine = df[features].copy()

df_mine.head()

# Binning 3 khoảng bằng quantile
for col in features:
    df_mine[col + "_bin"] = pd.qcut(df_mine[col], 3, labels=["low","mid","high"])

df_bins = df_mine[[c+"_bin" for c in features]]
df_bins.head()

df_hot = pd.get_dummies(df_bins)

print("Shape (one-hot):", df_hot.shape)
df_hot.head()

frequent = apriori(df_hot, min_support=0.1, use_colnames=True)

print("Số lượng tập thường xuyên:", frequent.shape)
frequent.sort_values("support", ascending=False).head()

rules = association_rules(frequent, metric="lift", min_threshold=1.0)

print("Tổng số luật tìm được:", rules.shape)
rules.head()

rules_filtered = rules[
    (rules["lift"] > 1.2) &
    (rules["confidence"] > 0.7)
].sort_values("lift", ascending=False)

print("Số luật sau khi lọc:", rules_filtered.shape)
rules_filtered.head(20)

plt.figure(figsize=(7,5))
plt.scatter(rules["confidence"], rules["lift"], alpha=0.7)
plt.xlabel("Confidence")
plt.ylabel("Lift")
plt.title("Biểu đồ phân tán của luật kết hợp")
plt.grid(True)
plt.show()

import networkx as nx

G = nx.DiGraph()

for _, row in rules_filtered.head(15).iterrows():
    for a in row['antecedents']:
        for c in row['consequents']:
            G.add_edge(a, c, weight=row['lift'])

plt.figure(figsize=(10,7))
pos = nx.spring_layout(G, k=0.4)
nx.draw(G, pos, with_labels=True, node_size=2500, font_size=10,
        font_color='white', node_color='steelblue', arrows=True)

plt.title("Network graph của 15 luật mạnh nhất")
plt.show()